#################################
# Plugin criado por Naur        #
# Para o servidor GuardianCraft #
# Discord: Naur#8062            #
# E-mail: naurzeraa@gmail.com   #
#################################

Permissao-bypass: "gc.admin"
Censurar:
  ativar-modulo: true
  substituir-por: "(censurado)"
  censurar-palavras:
    - 'pqp'
    - 'fdp'
AntiDV:
  ativar-modulo: true
  mensagem-com-palavra-proibida:
    cancelar: true
    simular-mensagem-para-quem-enviou: false
    ## A mensagem abaixo só será enviada caso a opção de simular-mensagem esteja desativada
    mensagem-cancelada: "&cA sua mensagem não foi enviada por conter a palavra proibída %palavra%"
    mensagem-para-staffs:
      - ''
      - '&cO jogador %player% enviou uma mensagem com a palavra proibída: %palavra%'
      - 'A mensagem completa foi: %mensagem%'
      - ''
# Para não ignorar nenhum caractere basta deixar como: ignorar-caracteres: []
  ignorar-caracteres:
# Atenção! Se você ignorar o caractere "." o plugin não irá reconhecer as palavras proibídas com ".", como ".com" e ".net"
#    - '.'
    - '-'
  palavras-proibidas:
    - '.com'
    - '.net'
    - 'minesv'
CapsLock:
  ativar-modulo: true
  porcentagem-limite-de-letras-maiusculas: 50.0

cobrar-mensagem:
  ativar-modulo: true
  enviar-mensagem: true
  mensagem: "&cVocê pagou %money% para enviar essa mensagem."
  mensagem-sem-money: "&cVocê não tem money suficiente para enviar essa mensagem, custa %money%."