name: GC_Setloja
description: This is a private plugin made for GuardianCraft.
author: Naur
version: 2.0.3
main: com.guardiancraft.gclojas.Main
commands:
  setloja:
    description: "Define uma nova loja para o jogador."
  delloja:
    description: "Se o jogador tiver uma loja, remove ela. Também pode ser utilizada para staffs removerem a loja
    de outros jogadores."
  loja:
    description: "Utilizado para teleportar para a loja dos outros jogadores."
  lojas:
    description: "Abre um menu que lista todas as lojas do servidor."
  fecharloja:
    description: "Fecha a loja do jogador. Também pode ser utilizada para staffs fecharem a loja
     de outros jogadores."
  abrirloja:
    description: "Abre a loja do jogador. Também pode ser utilizada para staffs abrirem a loja
    de outros jogadores."