prefixo: '[GCLojas] '
permissao-para-criar-loja: 'criar.loja' ## Deixe em branco caso não necessite de permissão para criar uma loja.
permissao-teleporte-com-delay-reduzido: 'delay.reduzido' ## Caso isso fique em branco, todos irão teleportar com delay reduzido.

mensagem-sem-loja: '&cUso correto: &f/loja (nick) &cou &f/lojas &cpara ver a lista de lojas'
mensagem-sem-permissao-para-criar-loja: '&cApenas VIPs podem criar uma loja!'

titulo-menu: '&3GCLojas - Página %p' ## Importante! Pode alterar o nome do título, porém ele precisa obrigatóriamente ter "Lojas" no nome para o funcionamento do plugin.
titulo-cabeca: '&6Loja de %player%'
lore-cabeca:
  - ''
  - '&7Esta loja está %status%'
  - ''
status-aberta: "&aAberta"
status-fechada: "&cFechada"
name-previous-page: "&a« Página Anterior"
name-next-page: "&aPróxima Página »"
mensagem-fechada: "&cVocê tentou se teleportar para uma loja que está fechada. Aguarde até o dono abrí-la!"
msg-status1: "&cA loja já está fechada!"
msg-status2: "&cA loja já está aberta!"
msg-abriu: "&aAgora a sua loja está aberta!"
msg-fechou: "&cVocê fechou a sua loja com sucesso!"

delay-teleporte: 4
delay-teleporte-vip: 2 ## Qualquer número abaixo de 1 se tornará um teleporte instantâneo.
mensagem-se-mexeu: '&cVocê se mexeu e portanto o seu teleporte foi cancelado.'

mensagem-teleportar: '&eVocê será teletransportado para a loja de %p em %s segundos, não se mova!'
mensagem-teleportado: '&aVocê foi teletransportado para a loja de %p.'
loja-insegura: '&cA loja que você tentou ir foi considerada insegura, tente novamente mais tarde ou entre em contato com proprietário.'
loja-insegura-dono: '&cA sua loja foi considerada insegura, tome providências para que outros jogadores consigam ir até ela.'
loja-definida: '&aLoja definida com sucesso!'
loja-redefinida: '&aLoja redefinida com sucesso!'
loja-removida: '&aLoja removida com sucesso!'
sem-loja-remover: '&cVocê não tem uma loja para ser removida.'
sem-loja: '&cA loja que você tentou ir não existe.'

delay-usar-comandos-loja: 5
msg-usar-comandos-loja: "&cVocê está tentando utilizar os comandos rápido de mais! Tente novamente em alguns instantes."

contador-de-paginas:
  ativar: true
  nome: '&aPágina %p'
  slot: 4 # Atenção! Use apenas slots de 0 a 8.

range-verificar-lava: 3

permissao-staff: 'gc.staff'

registrar-lojas-na-config-ao-setar: false # Caso esteja true, toda vez que for criada uma loja, o plugin salvará em "lojas.yml" (pode causar lag)

registrar-logs: true